added parameters (user_key and app_token) check

diff --git a/pushover b/pushover
--- a/pushover
+++ b/pushover
@@ -60,6 +60,20 @@ then
         fi
 fi
 
+if [ ! -n "$USER_KEY" ]
+then
+	echo "Error: Pushover user key not set"
+	echo
+	exit 1
+fi
+
+if [ ! -n "$APP_TOKEN" ]
+then
+	echo "Error: Pushover application token not set"
+	echo
+	exit 1
+fi
+
 if [ -n "$STDINPUT" ]
 then
 	MSG=$STDINPUT
@@ -85,8 +99,10 @@ then
 		exit 0	
 	else 
 		echo $RESULT
+		echo
 		exit 1 
 	fi
 else
 	echo $COMMAND
+	echo
 fi
